version: 23.12
server:
  ssl:
    key: ks:server_keys/server_key
    certificate: ks:server_keys/server_cert
definition:
  id: 1
  name: OIDC Definition
  grant_types:
    - authorization_code
    - password
    - client_credentials
    - refresh_token
    - urn:ietf:params:oauth:grant-type:pre-authorized_code
  authorization_details_types_supported:
    - type: openid_credential
      strategy: sha512
      script: null    
  ignore_unknown_authorization_details_type: false
  base_url: https://isvaop:8443
  token_settings:
    issuer: https://isvaop.ibm.com
    signing_alg: RS256
    signing_keystore: isvaop_signing
    signing_keylabel: rsakey
    access_token_type: jwt
  features:
    consent_prompt: NEVER_PROMPT
  ropc_mappingrule_id: ropc
  pre_mappingrule_id: pretoken
  pre_auth_settings:
    pre_authorize_code_lifetime: 1800
    require_transaction_code: true
    transaction_code_charset: 123456789
    transaction_code_length: 4
logging:
  level: debug

authentication:
  endpoint: ""
  callback_param_name: ""
  subject_attribute_name: ""
  credentials_jwt:
    signature_validation_enforcement: false

# ssl:
#   certificate:
#     - ks:rt_profile
#   disable_hostname_verification: false

jwks:
  signing_keystore: isvaop_signing
keystore:
  - name: server_keys
    type: pem
    certificate:
      - label: server_cert
        content: B64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUzRENDQXNTZ0F3SUJBZ0lKQU4zMHd1SVBEb3VlTUEwR0NTcUdTSWIzRFFFQkN3VUFNQkV4RHpBTkJnTlYKQkFNTUJtbHpkbUZ2Y0RBZUZ3MHlOVEF4TURnd05EUXpNemxhRncweU5qQXhNRGd3TkRRek16bGFNQkV4RHpBTgpCZ05WQkFNTUJtbHpkbUZ2Y0RDQ0FpSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnSVBBRENDQWdvQ2dnSUJBTm1vCk9wclRhbkt5Z1hOSm9UOTJiSUxtNXdjdmVTeDNzR1RFTE5SSnFzcWJidjdJMHo2TUJWcU1zYzcrMXM0OWlEUmEKM2tjY3JsTWVxMUVQdy9zUHpKakN5c203c3ZPMTViTlNQWlBCSXA5dDFIRUpOWENqVGV4UHo1NTNReFo1MklQUwozWE85R3BVdGNEeFFrN0FkeHVoVXFCd29odEVTYnNHdC9jdUs2VWwrNkpCUW8zUEdWNkc4VHFuOWw5a3l5bWpXCjRkNDJ5TVk1YnRmSFF6MTVVTWJaMDVrN3BHbkhEQjk2VW40QzlhS1FwczVGRktiRFhaRWVkL2NPRXp1M2RsbisKU2VTTUw3NlRFd1FGRFEzL0E2NUp1TWh5R0RyeE8xd1BKY2FwRm8wMGUwdW01VkZhYnRqbGtVRE5SUzlNYW92WApKL2xiR1BuMHFPUjlzSEtSY2ZQY1I2N1pkZEJSeFJQVEZVWUtzWFkraUVsYjBucnhIZTBVU1lHWGRZdnpGMEMrCmxtRGovTTJmZXBFOTcxWUsrdkZad051TFZkWk5hbzNUa1QvSzVZSXFBVlZRK3V0a2FBdFd5K0ZZSTQ5S1Vsb1MKSGI1Mnc0eHRLa2I4RUlkYXpndE1wV3hkVkJaalM3b2crWjNJdE5xM3hZYnJyOFdZUlhkVWJBU05majNKSUYrdApEQW5rR2puZjhHOEV5d2FTQlNVTGJWMGhlWEFxYWtaSm9xRFZMKzZCb2FRQnZwN0NISVkxZjYyUm9vWGNLdGxECmFmelQwYnE0cWpJd0RBWEptMlY0VlBXbTVObVB2aXV4bGpBeGtnOVFOMi9JNGlpajZRdUNKOEhCWlZTczlBRysKMVVkcEVud1kxdXRZd1FpcUkxTjZ4UXJna0ZOSVlNM1NxUE9lMXZ1TkFnTUJBQUdqTnpBMU1Bc0dBMVVkRHdRRQpBd0lFTURBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFUQVJCZ05WSFJFRUNqQUlnZ1pwYzNaaGIzQXdEUVlKCktvWklodmNOQVFFTEJRQURnZ0lCQUViTXpMSDdjZUVTekl0OEdIcnlGQTNOOFRYdkNrK3RTdzYvY0g3dktEYk4KdHo2bmE5bm9EZFhWMmdSQ2pYK1lENm85bVlqUmk0blMxK3gzL1F1WGpFbE15YlhJMXRnano3aWF1alZmaS9STApyNmxZdjI0elhmNWRFWm5BUHRidDAxQVEybm80VFRBVzRxM2pHYVNtT2NJaHhmaFhpTUsvSmtRcnI4ZFg2VURIClNqUzVJUm1iWVAwQzJiNURXakJiZ283QXBPL0FzQnE4OTNzT01TaDJiMFFreU5zSVp1clh5cDlpOTZKcGZ2eTYKbnE2ZmZEQmFEc2R0bllDLzE0OHFJZ3NzRnI2N21kc1UyNDlrUld3YzlDQVYrQWtveUE1OFpid3pPL2VyaUcxZApZWm9mRnhiQ042QlUxemtSOCtUSGhGVzBBRlBjYnJQNkVBNnhad0JGQ1RCd0loK0dPV09VQjhBUUE4ZXBhR3RiClB5RGhWS3VaejdkeG1WbDdPWkNJa0l4VXlrWlp6M05mK3VvQm5sR3lwbUJBOG4wTFF3UWhJZFI2THhPczhHY0kKVTJjaVVlcGh6Si9PTEtua2lMb2lsWHJEWGVpV2hTczdLREhGcmh3ZnJQaXphWjN3SHpuczN1VUZDL2V6U1lRTgpoVGN5cUhqWkE2OFFsSEpJWE9JMDYzaGtBbEFIQUV0MSs1Mk5LZk1DYnRlOFBGQ0grTjRleEhQYjdlU2pMRW80CnNteFhoMUtNYjU2WmlMNHF0M1JtV3BCd3JFcGdTRkxOaFp4OEk3T2JNaGlBb0c5VUJrbGFTWVB2ZFhDQ2p5S04KWmhVNXVkUTVyT1BFVWdncVdyNU83K3ZCZkpGLzRPWEo2TEV0RjNHdCtzSE5Jb1FmTWhBYlVVc05EWkdsdHlXSgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==

    key:
      - label: server_key
        content: B64:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1N3d2dna29BZ0VBQW9JQ0FRRFpxRHFhMDJweXNvRnoKU2FFL2RteUM1dWNITDNrc2Q3Qmt4Q3pVU2FyS20yNyt5Tk0rakFWYWpMSE8vdGJPUFlnMFd0NUhISzVUSHF0UgpEOFA3RDh5WXdzckp1N0x6dGVXelVqMlR3U0tmYmRSeENUVndvMDNzVDgrZWQwTVdlZGlEMHQxenZScVZMWEE4ClVKT3dIY2JvVktnY0tJYlJFbTdCcmYzTGl1bEpmdWlRVUtOenhsZWh2RTZwL1pmWk1zcG8xdUhlTnNqR09XN1gKeDBNOWVWREcyZE9aTzZScHh3d2ZlbEorQXZXaWtLYk9SUlNtdzEyUkhuZjNEaE03dDNaWi9rbmtqQysra3hNRQpCUTBOL3dPdVNiakljaGc2OFR0Y0R5WEdxUmFOTkh0THB1VlJXbTdZNVpGQXpVVXZUR3FMMXlmNVd4ajU5S2prCmZiQnlrWEh6M0VldTJYWFFVY1VUMHhWR0NyRjJQb2hKVzlKNjhSM3RGRW1CbDNXTDh4ZEF2cFpnNC96Tm4zcVIKUGU5V0N2cnhXY0RiaTFYV1RXcU4wNUUveXVXQ0tnRlZVUHJyWkdnTFZzdmhXQ09QU2xKYUVoMitkc09NYlNwRwovQkNIV3M0TFRLVnNYVlFXWTB1NklQbWR5TFRhdDhXRzY2L0ZtRVYzVkd3RWpYNDl5U0JmclF3SjVCbzUzL0J2CkJNc0drZ1VsQzIxZElYbHdLbXBHU2FLZzFTL3VnYUdrQWI2ZXdoeUdOWCt0a2FLRjNDclpRMm44MDlHNnVLb3kKTUF3RnladGxlRlQxcHVUWmo3NHJzWll3TVpJUFVEZHZ5T0lvbytrTGdpZkJ3V1ZVclBRQnZ0VkhhUko4R05icgpXTUVJcWlOVGVzVUs0SkJUU0dETjBxanpudGI3alFJREFRQUJBb0lDQVFDWWpMVU9nTER4MUxTd0JlSVRKY0FsCit3bmZXbUdXVGdqK2h4UlljWTFYMVpyMHpmSm91eUNoZDB6RUpJNlBIRWRUVW9ESjNJczl6SmdNQjMyM2dEcEkKc3ZZSWNCcWJmMWlQMTBzN1BMazBmbmpRQk1GRXdlQkNpU21lQ2o2bUNSNDhQbFZoNGg4NGdSRlI1TE91VXlCdgpBNjZUbGIvdjF2aHpuS3Z0dGQyTjJubkxkQWtyZ3M4MmwxR1hDUnNkYXVDOG5DYlFaUnRRK3ozNTFEb0hZdmkvCmRqbzlBclZZUWQ3NFRQWjJSVUs5L3A0Nm9lWTRmMk1iNi92dTF4bVoyQnNHTmhpNks1cm0raFB3MUUxekN0SWMKbktUN01DUlZZMi9VTlBXb0NDaTdMUlpoVG9jWS9zWUVGTm82VGVSNG94bG1DNVdEeWxwMkRnazFvL1pBUmpwVApna0VkVG1NWkE4Tkc0L0orVms2UEs0WFNROExjSlMreW9GY1JpOG1acXZpVkpPMTdiQTk4R2toZkZnWUNFWW04CkRhMWRzRU9RRGwrb1ZhbjE5bDliSzJUMWo4QmdXc1huVWhTT3BCanY3YTE4S1dWMEJEOXpqbFZKYkRiN3RFYUQKeEt5Q21TTzBERzg4dlpzNUxyS3gxWWl2NWg1dmJwamdXc2dXRDhqUkxsM255MjZmZGdnU3dvRUJxSEFiOXVuQgphYi9mYUFnMVdvdTF1UEpCZDcxK0xKZWkzcWwyM2tNWENEV1NoOTBKOXNjd0lOZFErU21pUEtiQ1VmdHp4ZklVCmFkY2kxNk5YNzNMaDREL0dObVVjQ09hYWw3d1Z4eHkvRDdsRnJFYVgrQ2srNVl3MUhRSW5qYlBYSDdXUFN0aWsKYnZiOGRMWDlhRk1VUGVycHI5NzRvUUtDQVFFQTk3eXhDSkxUcHEwaGRYSWpQT0xLRm1nWG1Bd29FU0lWSUYwRApndy9NdWpSVUxuUTVrN2tZVlgxV3JLK1UxTDlsaEpGaFFVdmZ4U04zODBlNHR4U2NvZ09WMTVBQm9QWFByRHFYCkZuNmsxajFQN0o0dGpUNlRjenRyMThYMDdUVnNTWXVuRlNEbUxuMUkvc3BpTk1SVStGemNrUkowOE1zaUxNVTIKN2dqUWFzbkh1Qms3bFJxVG5OMGgwTExKNUZ3RDNXdEhTM2VJY0o2dVBsUjJTUUZUazh4NkpvOFQrQjlEbFhJTgpyMVQxL05nZGt1aVQzRmVoRzZHTXh3K3V0Vk9PV25SNUQ1UXJqWjFpNDhhYjA1Z0RBeWV3SXd2a0thb0Vud210CkpFbEEzalYzVSs2M3F2UktIb2syUldhN1kxUmxRVkRrSit5VUNIVGhGOU5ZQytJYkNRS0NBUUVBNE9xekFKWXEKM3o5SG1tVkdvdElkT1BmcXhpQStrNXVQUnIxY0JDbFlvQVVEK1VnelppbWltOFoxSXFhNHVlZGJraW5zczJFTwpSUDk3R2xJWi9SanBoMWdPK3NJa0RHN2s1U1pJbVBWYkN1T0ZmWmtnN3pVS2QzVGhIb0VBYXB1TzNBcUs4cWlpClY0S043b3c1bVl3SVFkZ2lvNFhra0pTMHQ1cFFjazNoQitsOU0vUGpRVTY3RFl0NUVaalc2TDFVeE82MkpkMUUKL2NkS01URm56ZHZEZkZnS0lDTWNVN2t1S2ZDU2U3ZU5FMWdGMU5YcCtjREkwSy85d3BLZ1loR0lIdVk2bnVxSQp0UWNPV2xWVGJQZWNNQkRDbmRNR3ltNnpReUlRTU9WMUV5WjBpRUU2KzI4dG9ESitZeEI0elZVUC9XanJLLzU1CmgvVzFWaUp3TnZjSlpRS0NBUUJ3blA2Z2xoWE4rMzl0SXVBdnlpdncrWXBZSEphT0N6OHRRZnJadGZIclp1UXAKWmIzU2o5NG01bDNqQzhHTTRDQW1uZXRtd2pYTEtHOWJVR3dBRlVlS1FqVDRFMGNhUXdNUEdHY2IyNS9VbjNSWQpiQ0xxeE5wRUZHdldYdThTY1NseldSOHZkSkFONi9lbGtwd0h2b09kanFEWTlWbmhKNFcyY2tPZytySzdDRlJZCk5HZ29SRGQ3bysyK0w3ZWtyY3MzK0k4bEdBWVdvNXN6VERPa3hneVc3K2xLNDlsQS9mMDd6dWUzbnRoZkFtS1gKS0ZBbVpsTWUrMVhDR3pmZ3gwVzdpcHlKWDJKWThvVkVZMERzYzNwVEVkUjRhZXhpb0IyUHFkZGgya2E1ZS9adApXZU4xdTZ5QnF2L1hsblp5RmFnZGc4YmkreURqb3pXN0hlQTFMcWY1QW9JQkFHWjd5dENMbkVGWkxpRTE0SGUwClVjaHhmcktFWXI4VGRMZUE5UHFZZEYrRnFZZmUxRHpLMytNbkRKeWJaelNlTE9WdTRRSGpTWU02L2piQ0RrRjcKSm4yYkxFZ3FTZzY0UU9nQkI3ZGFwUDlUS0xKUUllZWRQWVdzNWg3bUhQQjJyU09xVWlHN29TMUt1YTFtaTZCaApaQ25NZUF3V3FFMFExVCtMdXZnNmNEMFFzUklKSVJYUzcveDkvczU3M0FEMHREbC9vOU9nL1J5OXdCcW1MbXhvCnBLeDEyVGRIaUZMRjREa1ArMDhRRmVJb2k0K3RZUTJDUUg2R2twUWtCNXhuN0tSWHQ0Sk56N2pjM0RkaEJjQnoKR3VIejRSblUzQlZGVjcxUk9odHRrbWtGYnJmZk1TYjhROGZvK2huZG1ZM0dJcUVQTzRreVRPSWNuV0lBRXkyWQpadGtDZ2dFQUVlclBmdXQ5N1RYLy9qS1lkRWVUczJNcnllQjJxbnVMQWdxWTdTcVpIT3BxMFNCSktUOXZPTEFTCjRPbjUzQUl1M2Y3TDZBUE0vdDVvaytuYVpMcDM2ME02S3ZwcHJudk84U2ZVeUVMRzU3Ujl0TTBCV3RuRUx6VHgKdW1ZY1grZm9YSmswOXhmbVhXUU1Bb0hwcVhuNFliYm5UcnhmR3pjNEpMTElxRjIrOHV6ZlVGZGREMXM2TTg5Sgp2ajBid0txV3l0dWdOdXVuSGFHK003bmkzeXRPTkhiTzcwQ1JESEw0alVDVzF1Vkp0ZVh6VTBEclU0eCtlKzA5CkIvb1luWmtKNG1IWURRdVYvZE1iR1dzamVrVEZ0V1hmNzJZVThMTWZBNzIwNVRsMkt5MEUyTmZHazBFUGZLUTAKMTFqTzJXNGlMNUlNV1hXank3eDdMdUhlZU1sN2t3PT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=

  - name: isvaop_signing
    type: pem
    key:
      - label: rsakey
        content: B64:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRRE9BQ0I0cW81ekpEVUsKY1NCcnM0ZTRMWVR2N3ZraFhsa3psUXlpNkwrUzZ4NGthY3Q4Ry90cHFtaHN3VFdleloxRnB2eFZod1FLcm9GVQpPK1hrM2loL0tpdzFDUFc0UVgyS0w0Z1hwamJsbElEWkdVeGhFMzhOQ001bFdMZTA1OStNbFRxL1dxMGdEWjVCCkxHYUhJMG5XZkVTZ1dwK2srOVZTTnNLRDJSODJpRkVnU1U3NDlVOUtmU1huczFsWGNqNmNqNUJSOXhuOVcxUHgKUzljSGtmeXp6bXl6Qy9TUU5SQ0NmSXE0WU54THJnbmgyZitKMUl5eFRsVE1lanpiV0V3NmQ2RVFZdmU0OW5hMwpVMUU2aWttQmwxanc5NVQza09jY3U1ZDQwNWZSejkwRmVjbGJmMEUxRDB0N3B3amt6NnNhSEFuTXJJTHp0UTJxCmVzcy9RWUhWQWdNQkFBRUNnZ0VBSjZEM25pNzFZMm9hT0EyR05xSGRZSTJGTHVFU2xSeEEzYjcxSk52UWl0Tm4KUTRzRXBiWCtXaGY1cWI1TGNlYk5OQXFKTFd6aFZxcTJYMzE4WHRoc0F2YWFkWU5wUGM1L2Q1ZG9QMkJ1M0NDQwozd0RTWkRScmN4YjRHYUFGQ3l5MklTWE9IT1MxUEY3U1RHaGR1dTZMZEZNSW9xNThXckZGbXVERTc3ZFRuVm9vCkx6bkltQ2grRTJJYWZoRTF6WThDQnZnWGRWdjNwQzRzV0toTmJzbTRKUGc2NDN3ZWNmbXpUY0xrOERZOCtJOTIKTG9nVjlEUVA4VU1EeHM4VWpNU1ZmQm9qT1grYzFkL00vOUZ5YVprTEc4Y2NuYTFidlZUb2pLTFlIamo0cWdERApETXF2N3I3SEdZRWNWYmNEdUZkUFhoYVVRaTV6empHVVZEdHI4RmszaXdLQmdRRDkvWG9VYjdTeUdEL1dxeEI4CndpOEVJNXBtOXVkZ1l5Zko3UTdlaTREbytUYnJYMGRTdjRldmV2em9ySkhwY1E2d005aVpvSDRaYjBjeVY0TU4KcDAwNDVwd3ZFWHhrUEx0MEJaRDlTZ2JJZ0lOUE4yWldFbnpnWEw5TXJrVzhIaGsxOFlGWlMvRnVxM3VEcnFIWQp5Y2d2MUFTc3hBT1p3U3NqN2dWOGJVRExtd0tCZ1FEUG9XODM1Y3JaS1JreTdYM3JMVnFNSVlwbHVYNDZFa3FECm5SZ1FWTnFiK1Y1Ulp2VGVjZkNJaTFqMUZUSXYvTWNJUVZzckh4MjcvczdMNjBIbW4vUVZyZURyemd5Y2lCWUoKZVZUZ2t0aU1mWk9CMDBaRkVGWDRjYU92T3Z1eE9VTndXcHVvYmdwd2pGQnc0eUxJeU56b050VTJMSmlWN3FrQwpuODFoQk1OWFR3S0JnSFg0amdOLy93WFpqWTAvMTJDYk1RdFRIaHhGQWlNYTZ4ZzNLM2ppZ3ZXekMzYzN3Z0VGClJSaVVuM1BTODlMaDJGaXZQQ1BmRDdMd3BMa1ZQS0hTMjJOYWVhRERGbXZZYVpqeUhPNEl2QzNVd3lqQUtxQS8KNWhDd0E0cXlSMkdnK1VTODc3OXlMcW1nckxYMUh1ZDZrYWpsYVdaMWhOYWRpbFFkOGg1aEFIK1JBb0dBY0hXbgpFT2ExSlVSZWNyZ3g4TFREQzQyTE1hZnoxNjVhajhrQjVLNmhMY1Eyc3U2S0NRWTcyeWxteUhCdm01QlZtWUlVCnlGbDFPSU0rTFROQ29aRFhtdnB3RGlpdnFnVUhzcC8yT2lFdmk0RGs2WGV1NHUrRE1Tc1VGbkJqTFUydjJtWXAKVTJRdTRXRU9uT1paeTlrSDFmc0ZKdSttd2ViZndoMGVGOE9Gcm44Q2dZQm0zSVkyY3Vac0hWdkVFNFdRTE5oWgpoTENpbzNBbTJWNUpJT0t4cTBGS240UlVjYVZqUVROTWErNFgxL3h3ZS9VUUdsSzNvL3ZOdnJ6VTgxQzlMV1NvCjVHbUlWWi9xN0pCc0NheHZMMzA1OVJlc2cvaVFKbVVoL1RrVDFsZW9KSkpZbERCV1lxSU4rcjVLZGRBc214cUMKNnpjUSthUU8wZENiSHN0RFhMTXgzdz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K

  - name: postgres
    type: pem
    certificate:
      - label: pg_pub_cert
        content: B64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU0akNDQXNxZ0F3SUJBZ0lKQU0xbzlzYm54VGxJTUEwR0NTcUdTSWIzRFFFQkN3VUFNQk14RVRBUEJnTlYKQkFNTUNHbHpkbUZ2Y0dSaU1CNFhEVEkxTURFd09EQXpOREl5T0ZvWERUSTJNREV3T0RBek5ESXlPRm93RXpFUgpNQThHQTFVRUF3d0lhWE4yWVc5d1pHSXdnZ0lpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElDRHdBd2dnSUtBb0lDCkFRRGNRNVhYQnJNd0pmYXNwdkNxYTJkSzJoWUorZzhKc0pmbG5UcFJSVlRJN2Q0QzRlMmd6WlZONGNXQjFvNWEKVVBsT2I4bDd2K0JGakR0eU1Cdy9WRjIra1NiSjRNTDdNR245ejlBdnNZL0o5VFhZZjRVK25aVjNlODJKRU5qZApyMndBV3M5TzNheWZ1NU1MVjFtOG4zK0JFUmg5STBvQTgzVEl2aTg1WGh1WlRnQTlhM01MbkRhUGNjV2xVdEF5Ci93MEUvWk1LbE5nK3gvUmhjbUZ1akV5aXM2TnRmaSt5VUowaDFSZWNzNkhXK05HMDJpWFVVQksvQkZZRGFnTkMKWVh4SG14bHhPZ3ZLaGZROWVpV1pXS3E0b1ZrY0xLc2xPOVBzSko4aGM4UGNNQ0JrR1RYNzhFSk1YR3ZlN3UxRwo2ZXpaTGoyeW5MSitBeUg5QTF0enBHZ3l5R1JOWHVXc25WWE0vS1JhQnBlbVJmVG9rdXZGQ2t4UTBrMFRiZzg2ClE3NzJEMEVOZ1FlakhTRkVWcWFHMDBZcjg1cm5mWTBxOGt4aUN1OVM5dHNDcS9GVFJJQUYxQzJJQXZrYXJRYnYKbm82M0hCSUpXa0hScUNPaDlxbkVwcTFqb1ZiQkVtZ1lMVlhEQTF1VFpTN0h3TGRXVG5zdFQ0ckp5UnhVajlVUgpwckZsK0wwVExMdmUrb2FuWWwzajhBRXpIanZNVlhuNkZQeVZURUhRRkN5ZjdleEptUU8ySjVYVFJqV2VJeDNGCkVodm9zM3Q3VzNCUFFHb1JwNE1Xc3ZLTVJpNEdFTzdZb0dvL3UxSlZOWWdaeEFhZkpmSytTdzRuNDg3NU94MHcKNDlVMFVlNnZWLzJwRmJDUHB5VXBKZ1ZXSFlxWnBQUWNiQ2w5M1FnbEdYVmp4d0lEQVFBQm96a3dOekFMQmdOVgpIUThFQkFNQ0JEQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3RXdZRFZSMFJCQXd3Q29JSWFYTjJZVzl3ClpHSXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBQ1cyZHRwbGRBOEs5MDF0cVhjaDl3d0ZIb1E3elFwY2VDSG8KZ1pwcUxUaVRIdk5idkRpYjYwMi9oWUVSRDVJaU9aM3VuaVYyY3NBdytYWkZ6NHk3YVk1anUydDZyRHp4RmlocQpmaDVUL216THgrYzA1dENTalY4UGU5bnJ2ZmN5b1lTSzNDaytsdE5ROElJZUtNak9xd2xIRVZTTnJpN0xRcFNXClNJSndDTHFqRnhnN0dyNEYyeUNTTmc3NTRjQnhsbkN4TUJpOTlCSU5tOFRHcVAxNXByVmtERHBFcUVlZWpQdFUKdy9VM05UOXB4S1lPSXhTR1ZZeHkxWE9OOVdXS2pLeFdNQXhiTmFDUEMrbjZVaWVmc3NCUFptWEdXQzh6TU5OVgphVVhrTlpGRU5vbGNmT0dRU2tRM1JtUWRyUi9jMU40S1NsKzZZSWo3K2FjeFg2WHd4RzFYQ1NsWFQxdlhmQ01IClR0b3dRcVNtelQ0eXk0c1JtS0hFbzVnaFBCUnVSWTduWHBHU0xYRTNJbDRjTjY1b1RQSUU2VXozU3M0VVhjN2cKS3NoUkdiRGJDZ3l2SHZXb2pSb2YyTkZhOXBKVlMxeDR1NlJZaW13NnlYTlVZSExodkRmTy9iVXc3eC9lVUMvbwptVzZFV2c5YWxsUFZQdC9xRDdUeVp0ZUhFcldERnBGbUc2Z3A1cHE2TVNDb3BxNFRBNHhWcHR3aCt1MFdjSDFlCkJGN2lmbTAxc3JxRnhxVlgxaUZtWlJjYUJndU9pZ2hWK1IwYktXMlkzYitmVW1pNUFJTGZmckw5ZTM2dHRRNDIKcCtNc2xWUUh3NmNldUE2OFJBdklTRzRTN0c3Y2FxY0h4NmtsRmtyNTFrUnJOWkVPSWZjV1R1WkFPSDVJenJ6WgpVVHNCVjFLMwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==

runtime_db: hvdb
session_cache:
  type: in-memory

server_connections:
  - name: hvdb
    type: postgresql
    database_name: postgres
    hosts:
      - hostname: isvaopdb
        hostport: 5432
    credential:
      username: isvaopuser
      password: passw0rd
    ssl:
      certificate:
        - ks:postgres/pg_pub_cert
  - name: ldap_test
    type: ldap
    hosts:
      - hostname: isvaopldap
        hostport: 1389
        credential:
          bind_dn: 'cn=root,dc=ibm,dc=com'
          bind_password: passw0rd
    conn_settings:
      max_pool_size: 50

ldapcfg:
  - name: myldap
    scope: subtree
    user_object_classes: top,Person,organizationalPerson,inetOrgPerson
    filter: (|(|(objectclass=ePerson)(objectclass=person))(objectclass=User))
    selector: objectClass,cn,sn,givenName
    srv_conn: ldap_test
    attribute: uid
    baseDN: dc=ibm

rules:
  mapping:
    - name: ropc
      rule_type: javascript
      content: "@ropc.js"
    - name: pretoken
      rule_type: javascript
      content: "@pretoken.js"
    - name: preauth_userauth
      rule_type: javascript
      content: "@preauth_userauth.js"
    - name: preauth_notifytxcode
      rule_type: javascript
      content: "@preauth_notifytxcode.js"

dynamic_registration:
  registration_endpoint_authentication:
    require_bearer_token: true
    allow_custom_client_creds: true
  management_endpoint_authentication:
    require_bearer_token: true
  registration_access_token:
    generate: false
    lifetime: 86400
    scopes:
      - cdr:registration

clients:
  - client_id: vcissuer
    client_name: OID4VCI Issuer
    client_secret: secret
    enabled: true
    grant_types:
      - client_credentials
    scopes:
      - cdr:registration
  - client_id: default_oid4vci_wallet
    client_name: OID4VCI Untrusted Wallets
    enabled: true
    grant_types:
      - authorization_code
      - urn:ietf:params:oauth:grant-type:pre-authorized_code
    response_types:
      - code
    authorization_details_types:
      - openid_credential
    act_as_credential_issuer: true
    redirect_uris:
      - openid-credential-offer://
      - openid-credential-wallet://

